databases:
  - name: scale-mqtt-client
    databaseName: scale-mqtt-client
    user: scale-mqtt-client

services:
  - type: web
    name: scale-mqtt-client
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: scale-mqtt-client
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false